[package]
name = "exchange-gateway"
version = "0.3.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
bimap = "0.6.3"
bs58 = "0.5.1"
chrono = "0.4.44"
data-encoding = "2.11.0"
ed25519-compact = "2.3.0"
exchange-types = { version = "0.1.5", registry = "shipyard" }
hmac = "0.12"
p256 = "0.13"
p384 = "0.13"
rust_decimal = "1.42.1"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_urlencoded = "0.7.1"
serde_with = "3.21.0"
sha2 = "0.10"
strum = { version = "0.28.0", features = ["derive"] }
uuid = { version = "1.23.3", features = ["v4"] }

[lints.clippy]
new_ret_no_self = "allow"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
features = []
no-deps = true
targets = ["x86_64-unknown-linux-gnu"]
